/** Auto-generated from openapi.json — do not hand-edit endpoint list structure. */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export type EndpointDoc = {
  id: string
  method: HttpMethod
  path: string
  summary: string
  description: string
  tags: string[]
  security: boolean
  bodyExample?: unknown
  responseExample?: unknown
  notes?: string[]
  params?: string[]
  responses?: string[]
}

export const ENDPOINTS: EndpointDoc[] = [
  {
    id: 'get-_health',
    method: 'GET',
    path: '/health',
    summary: 'Liveness probe',
    description:
      'Returns `200 { "status": "ok" }` when the process is up. **No authentication.**\n\nUse for load balancers / Kubernetes liveness probes.',
    tags: ['Health'],
    security: false,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_ready',
    method: 'GET',
    path: '/ready',
    summary: 'Readiness probe',
    description:
      'Checks Postgres connectivity with `SELECT 1`.\n\n- `200 { "status": "ready" }` when the database is reachable\n- `503 { "status": "not_ready" }` otherwise\n\n**No authentication.** Use for readiness gates before sending traffic.',
    tags: ['Health'],
    security: false,
    params: [],
    bodyExample: null,
    responses: ['200', '503'],
  },
  {
    id: 'get-_v1_me',
    method: 'GET',
    path: '/v1/me',
    summary: 'Resolve current API key',
    description:
      'Identifies whether the provided API key is **admin** or an **instance** key.\n\nUsed by the dashboard after login.\n\n**Responses:**\n- Admin: `{ "role": "admin" }`\n- Instance: `{ "role": "instance", "instance": { ...full instance including apiKey } }`\n\n**Example**\n```bash\ncurl -s "$BASE/v1/me" -H "X-Api-Key: $KEY"\n```',
    tags: ['Auth'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401'],
  },
  {
    id: 'post-_v1_instances',
    method: 'POST',
    path: '/v1/instances',
    summary: 'Create instance',
    description:
      '**Admin only.** Provisions a new WhatsApp session.\n\n- Generates a unique **instance API key** (`apiKey`) — use it for all session operations\n- Does **not** open the socket yet — call `POST /v1/instance/connect` with the instance key\n- `name` becomes the zapo `sessionId` (stable across restarts)\n\n**Example**\n```bash\ncurl -s -X POST "$BASE/v1/instances" \\\n  -H "X-Api-Key: $ADMIN_API_KEY" -H "content-type: application/json" \\\n  -d \'{"name":"sales-1","webhookUrl":"https://example.com/webhooks/zapo","webhookEvents":["instance.qr","instance.connection","message.inbound","call.incoming"]}\'\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: {
      name: 'sales-1',
      webhookUrl: 'https://example.com/webhooks/zapo',
      webhookEvents: ['instance.qr', 'instance.connection', 'message.inbound', 'call.incoming'],
    },
    responses: ['200', '400', '401', '403', '409'],
  },
  {
    id: 'get-_v1_instances',
    method: 'GET',
    path: '/v1/instances',
    summary: 'List instances',
    description:
      '**Admin only.** Returns every instance including **`apiKey`**, **`pushName`**, and **`avatarUrl`** when known.\n\n```bash\ncurl -s "$BASE/v1/instances" -H "X-Api-Key: $ADMIN_API_KEY"\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403'],
  },
  {
    id: 'delete-_v1_instances_name',
    method: 'DELETE',
    path: '/v1/instances/{name}',
    summary: 'Delete instance (logout)',
    description:
      '**Admin only.** Unlinks the companion device when possible (`logout`), stops the client, and deletes metadata.\n\nIrreversible without re-pairing. Prefer `POST /v1/instance/disconnect` (instance key) to stop temporarily.',
    tags: ['Instances'],
    security: true,
    params: ['name'],
    bodyExample: null,
    responses: ['200', '401', '403', '404'],
  },
  {
    id: 'post-_v1_instances_name_keys_rotate',
    method: 'POST',
    path: '/v1/instances/{name}/keys/rotate',
    summary: 'Rotate instance API key',
    description:
      '**Admin only.** Generates a new instance `apiKey`, invalidates the previous one, and returns the instance including the new key.\n\nUpdate all integrations immediately after rotation.',
    tags: ['Instances'],
    security: true,
    params: ['name'],
    bodyExample: null,
    responses: ['200', '401', '403', '404'],
  },
  {
    id: 'get-_v1_instance',
    method: 'GET',
    path: '/v1/instance',
    summary: 'Get own instance',
    description:
      '**Instance key only.** Returns this key’s instance (`apiKey`, `pushName`, `avatarUrl`, status, …).\n\n```bash\ncurl -s "$BASE/v1/instance" -H "X-Api-Key: $INSTANCE_API_KEY"\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404'],
  },
  {
    id: 'post-_v1_instance_connect',
    method: 'POST',
    path: '/v1/instance/connect',
    summary: 'Connect / start own session',
    description:
      '**Instance key only.** Opens the WhatsApp Web socket.\n\n```bash\ncurl -s -X POST "$BASE/v1/instance/connect" -H "X-Api-Key: $INSTANCE_API_KEY"\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_instance_disconnect',
    method: 'POST',
    path: '/v1/instance/disconnect',
    summary: 'Disconnect own session',
    description:
      '**Instance key only.** Closes the socket without unlinking the device. Next `connect` resumes without QR.',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404'],
  },
  {
    id: 'post-_v1_instance_restart',
    method: 'POST',
    path: '/v1/instance/restart',
    summary: 'Restart own session',
    description: '**Instance key only.** Shortcut for disconnect then connect.',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_instance_qr',
    method: 'GET',
    path: '/v1/instance/qr',
    summary: 'Get own QR payload',
    description:
      '**Instance key only.** Last cached QR string from `auth_qr`.\n\n```bash\ncurl -s "$BASE/v1/instance/qr" -H "X-Api-Key: $INSTANCE_API_KEY"\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404'],
  },
  {
    id: 'post-_v1_instance_pairing-code',
    method: 'POST',
    path: '/v1/instance/pairing-code',
    summary: 'Request pairing code (own session)',
    description:
      '**Instance key only.** Requests an 8-character pairing code.\n\n```json\n{ "phone": "5511999999999" }\n```',
    tags: ['Instances'],
    security: true,
    params: [],
    bodyExample: {
      phone: '5511999999999',
    },
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_metrics',
    method: 'GET',
    path: '/v1/metrics',
    summary: 'Instance metrics summary',
    description:
      'Aggregated messages, calls, media and storage for an instance over a time range (default last 7 days).',
    tags: ['Metrics'],
    security: true,
    params: ['from', 'to', 'bucket'],
    bodyExample: null,
    responses: ['400', '403'],
  },
  {
    id: 'get-_v1_metrics_timeseries',
    method: 'GET',
    path: '/v1/metrics/timeseries',
    summary: 'Instance metrics time series (for charts)',
    description: 'Bucketed message and call counts for plotting. `bucket=hour||day` (default day).',
    tags: ['Metrics'],
    security: true,
    params: ['from', 'to', 'bucket'],
    bodyExample: null,
    responses: ['400', '403'],
  },
  {
    id: 'get-_v1_metrics_resources',
    method: 'GET',
    path: '/v1/metrics/resources',
    summary: 'Live resource snapshot for instance / process',
    description:
      'Process memory & CPU (Node process), live session share estimate, and storage usage for this instance. CPU/memory are process-wide (multi-session); heap is split equally among live sessions when possible.',
    tags: ['Metrics'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['403'],
  },
  {
    id: 'post-_v1_messages_text',
    method: 'POST',
    path: '/v1/messages/text',
    summary: 'Send text message',
    description:
      'Sends a plain-text WhatsApp message via `client.message.send`.\n\n**Requirements:** instance connected (`status: open`).\n\n**Example body**\n```json\n{\n  "to": "5511999999999",\n  "text": "Olá! Mensagem enviada via zapo-rest 👋",\n  "linkPreview": true\n}\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      text: 'Olá! Mensagem enviada via zapo-rest 👋',
      linkPreview: true,
    },
    responses: ['200', '400', '503'],
  },
  {
    id: 'post-_v1_messages_reply',
    method: 'POST',
    path: '/v1/messages/reply',
    summary: 'Reply to a message',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_image',
    method: 'POST',
    path: '/v1/messages/image',
    summary: 'Send image',
    description:
      'Media source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n```bash\n# JSON + URL\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","mediaUrl":"https://cdn.example.com/a.jpg"}\'\n\n# Multipart upload\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" \\\n  -F to=5511999999999 -F file=@./photo.jpg -F caption="oi"\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      mediaUrl: 'https://picsum.photos/800',
      mimetype: 'image/jpeg',
      caption: 'Foto do produto',
    },
    responses: ['200', '400', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_messages_video',
    method: 'POST',
    path: '/v1/messages/video',
    summary: 'Send video',
    description:
      'Media source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n```bash\n# JSON + URL\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","mediaUrl":"https://cdn.example.com/a.jpg"}\'\n\n# Multipart upload\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" \\\n  -F to=5511999999999 -F file=@./photo.jpg -F caption="oi"\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      mediaUrl: 'https://picsum.photos/800',
      mimetype: 'image/jpeg',
      caption: 'Foto do produto',
    },
    responses: ['200'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_messages_audio',
    method: 'POST',
    path: '/v1/messages/audio',
    summary: 'Send audio / voice note',
    description:
      'Media source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n```bash\n# JSON + URL\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","mediaUrl":"https://cdn.example.com/a.jpg"}\'\n\n# Multipart upload\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" \\\n  -F to=5511999999999 -F file=@./photo.jpg -F caption="oi"\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      mediaUrl: 'https://picsum.photos/800',
      mimetype: 'image/jpeg',
      caption: 'Foto do produto',
    },
    responses: ['200', '400', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_messages_document',
    method: 'POST',
    path: '/v1/messages/document',
    summary: 'Send document',
    description:
      'Media source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n```bash\n# JSON + URL\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","mediaUrl":"https://cdn.example.com/a.jpg"}\'\n\n# Multipart upload\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" \\\n  -F to=5511999999999 -F file=@./photo.jpg -F caption="oi"\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      mediaUrl: 'https://picsum.photos/800',
      mimetype: 'image/jpeg',
      caption: 'Foto do produto',
    },
    responses: ['200', '400', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_messages_sticker',
    method: 'POST',
    path: '/v1/messages/sticker',
    summary: 'Send sticker',
    description:
      'Media source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n```bash\n# JSON + URL\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","mediaUrl":"https://cdn.example.com/a.jpg"}\'\n\n# Multipart upload\ncurl -s -X POST "$BASE/v1/messages/image" -H "X-Api-Key: $KEY" \\\n  -F to=5511999999999 -F file=@./photo.jpg -F caption="oi"\n```',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511999999999',
      mediaUrl: 'https://picsum.photos/800',
      mimetype: 'image/jpeg',
      caption: 'Foto do produto',
    },
    responses: ['200'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_messages_location',
    method: 'POST',
    path: '/v1/messages/location',
    summary: 'Send location',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_poll',
    method: 'POST',
    path: '/v1/messages/poll',
    summary: 'Send poll',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_react',
    method: 'POST',
    path: '/v1/messages/react',
    summary: 'React to a message',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_edit',
    method: 'POST',
    path: '/v1/messages/edit',
    summary: 'Edit a sent text message',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_revoke',
    method: 'POST',
    path: '/v1/messages/revoke',
    summary: 'Revoke / delete for everyone',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_contact',
    method: 'POST',
    path: '/v1/messages/contact',
    summary: 'Send contact vCard(s)',
    description: 'Sends one or more contacts as WhatsApp contactMessage / contactsArrayMessage (vCard 3.0).',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_forward',
    method: 'POST',
    path: '/v1/messages/forward',
    summary: 'Forward a stored message',
    description:
      'Forwards a message from the local store to another chat (`forward: true`). Text is re-sent from `body`; other types use the raw proto payload when available.',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_messages_star',
    method: 'POST',
    path: '/v1/messages/star',
    summary: 'Star / unstar a message (app-state)',
    description: '',
    tags: ['Messages'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_messages_messageId',
    method: 'GET',
    path: '/v1/messages/{messageId}',
    summary: 'Get stored message by id',
    description: '',
    tags: ['Messages'],
    security: true,
    params: ['messageId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_contacts',
    method: 'GET',
    path: '/v1/contacts',
    summary: 'List stored contacts',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: ['limit', 'offset'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_jid',
    method: 'POST',
    path: '/v1/contacts/jid',
    summary: 'Build JID locally (createJid)',
    description:
      'Applies local phone normalization (BR 9th digit, MX/AR) **without** calling WhatsApp.\n\nFor the **server-confirmed** JID, use `POST.../contacts/resolve` or `.../check`.\n\nExample: `5568981159096` → `556881159096@s.whatsapp.net`',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_resolve',
    method: 'POST',
    path: '/v1/contacts/resolve',
    summary: 'Resolve correct WhatsApp JID for numbers',
    description:
      'Like `POST /chat/whatsappNumbers`:\n- expands BR **nono dígito** / MX-AR variants\n- **one** `getLidsByPhoneNumbers` batch (no spam)\n- returns the WA-confirmed `jid` when `exists`\n- caches results (Redis/memory) for 24h',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_check',
    method: 'POST',
    path: '/v1/contacts/check',
    summary: 'Check if numbers exist on WhatsApp (batch)',
    description:
      'Batch existence check with BR/MX/AR digit variants. Uses a **single** usync call for all numbers+variants.\n\nAlias of resolve with a flatter response shape ( compatible fields).',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: {
      phones: ['5511999999999', '5511888888888'],
    },
    responses: ['200', '400', '503'],
  },
  {
    id: 'get-_v1_contacts_check',
    method: 'GET',
    path: '/v1/contacts/check',
    summary: 'Check one number (query)',
    description: 'single-number check: `?phone=5568981159096`',
    tags: ['Contacts'],
    security: true,
    params: ['phone'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_whatsapp-numbers',
    method: 'POST',
    path: '/v1/contacts/whatsapp-numbers',
    summary: 'whatsappNumbers alias',
    description: 'Same as `POST.../contacts/resolve` (legacy naming).',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_contacts_jid',
    method: 'GET',
    path: '/v1/contacts/{jid}',
    summary: 'Get contact',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: ['jid'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_contacts_phone_profile-picture',
    method: 'GET',
    path: '/v1/contacts/{phone}/profile-picture',
    summary: 'Get profile picture (durable storage + TTL revalidation)',
    description:
      'Returns contact avatar with **bytes in object storage** (deterministic key, overwrite on change).\n\n- Query `type`: `preview` (default, compact) or `image` (full resolution) — independent per request.\n- Within TTL: serve our stored file **without** hitting WhatsApp.\n- After TTL (or `refresh=true`): revalidate via IQ; compare `id`/sha256; download+overwrite only if changed.\n- Privacy / no pic: delete stored object (no orphans).\n- Binary stream: `GET.../profile-picture/file`.\n- Background auto-fetch (own profile + picture push) uses env `AVATAR_FETCH_TYPES` (`both`|`image`|`preview`).\nDo not spam `refresh` (WhatsApp rate-overlimit).',
    tags: ['Contacts'],
    security: true,
    params: ['type', 'refresh', 'phone'],
    bodyExample: null,
    responses: ['200', '400', '503'],
  },
  {
    id: 'get-_v1_contacts_phone_profile-picture_file',
    method: 'GET',
    path: '/v1/contacts/{phone}/profile-picture/file',
    summary: 'Stream stored profile picture bytes',
    description:
      'Streams the durable avatar from object storage. Triggers resolve (with TTL) first so the file exists when possible.',
    tags: ['Contacts'],
    security: true,
    params: ['type', 'refresh', 'phone'],
    bodyExample: null,
    responses: ['404', '503'],
  },
  {
    id: 'get-_v1_contacts_phone_about',
    method: 'GET',
    path: '/v1/contacts/{phone}/about',
    summary: 'Get contact about status',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: ['phone'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_block',
    method: 'POST',
    path: '/v1/contacts/block',
    summary: 'Block contact',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_contacts_unblock',
    method: 'POST',
    path: '/v1/contacts/unblock',
    summary: 'Unblock contact',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_blocklist',
    method: 'GET',
    path: '/v1/blocklist',
    summary: 'Get blocklist',
    description: '',
    tags: ['Contacts'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_presence',
    method: 'POST',
    path: '/v1/presence',
    summary: 'Set online presence',
    description:
      'Broadcasts account presence: `available` (online) or `unavailable`.\n\n```json\n{ "type": "available" }\n```',
    tags: ['Presence'],
    security: true,
    params: [],
    bodyExample: {
      type: 'available',
    },
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_chats_jid_chatstate',
    method: 'POST',
    path: '/v1/chats/{jid}/chatstate',
    summary: 'Send typing / recording indicator',
    description:
      'Sends a chat-state into a conversation:\n\n| state | Meaning |\n|-------|---------|\n| `composing` | Typing… |\n| `recording` | Recording voice note |\n| `paused` | Stopped |\n\nPath param `jid` may be digits or a full JID (URL-encode `@` as `%40`).\n\n```bash\ncurl -s -X POST "$BASE/v1/instances/sales-1/chats/5511999999999/chatstate" \\\n  -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{ "state": "composing" }\'\n```',
    tags: ['Presence'],
    security: true,
    params: ['jid'],
    bodyExample: {
      state: 'composing',
    },
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_presence_subscribe',
    method: 'POST',
    path: '/v1/presence/subscribe',
    summary: 'Subscribe to peer presence & chatstate',
    description:
      'Subscribes to online/offline and typing/recording indicators for a chat JID. Must be re-subscribed after reconnect. Events: `presence.update`, `chatstate`.',
    tags: ['Presence'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_calls',
    method: 'POST',
    path: '/v1/calls',
    summary: 'Start outbound voice call',
    description:
      'Places an **audio-only** WhatsApp voice call (`client.voip.startCall`).\n\nReturns `callId` immediately after the offer is sent. Progress continues via webhooks `call.state` / `call.ended` and the live PCM WebSocket.\n\n**No file / audioUrl playback** — open the stream and send live mic PCM.\n\n**Example body**\n```json\n{\n  "to": "5511888888888"\n}\n```\n\n```bash\ncurl -s -X POST "$BASE/v1/instances/sales-1/calls" \\\n  -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511888888888"}\'\n```',
    tags: ['Calls'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511888888888',
    },
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_calls',
    method: 'GET',
    path: '/v1/calls',
    summary: 'List active calls',
    description: 'Lists in-memory calls for the instance (`client.voip.getCalls()`), including ringing and active.',
    tags: ['Calls'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_calls_history',
    method: 'GET',
    path: '/v1/calls/history',
    summary: 'List call history (DB)',
    description:
      'Persisted calls for the instance. Use `withRecording=true` to only list calls with downloadable recordings.',
    tags: ['Calls'],
    security: true,
    params: ['limit', 'offset', 'withRecording'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_settings_call-recording',
    method: 'GET',
    path: '/v1/settings/call-recording',
    summary: 'Get call recording setting',
    description: '',
    tags: ['Calls'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_settings_call-recording',
    method: 'PUT',
    path: '/v1/settings/call-recording',
    summary: 'Enable/disable call recording',
    description:
      'Requires media storage (`MEDIA_STORAGE=local|s3`). Recordings are WAV stereo (local | remote) stored in object storage.',
    tags: ['Calls'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_calls_callId',
    method: 'GET',
    path: '/v1/calls/{callId}',
    summary: 'Get call snapshot',
    description: 'Returns a single call snapshot, or `{ "call": null }` if unknown / already GC’d.',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: null,
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_calls_callId_accept',
    method: 'POST',
    path: '/v1/calls/{callId}/accept',
    summary: 'Accept incoming call',
    description: 'Accepts a ringing inbound call (`canAccept: true` on the call snapshot / `call.incoming` webhook).',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: null,
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_calls_callId_reject',
    method: 'POST',
    path: '/v1/calls/{callId}/reject',
    summary: 'Reject incoming call',
    description: 'Rejects a ringing inbound call. Optional body `{ "reason": "..." }`.',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: {
      reason: 'busy',
    },
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_calls_callId_end',
    method: 'POST',
    path: '/v1/calls/{callId}/end',
    summary: 'End active call',
    description: 'Hangs up an active/connecting call. Optional body `{ "reason": "..." }`.',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: {
      reason: 'busy',
    },
    responses: ['200', '401', '403', '404', '503'],
  },
  {
    id: 'post-_v1_calls_callId_mute',
    method: 'POST',
    path: '/v1/calls/{callId}/mute',
    summary: 'Mute / unmute local audio',
    description: 'Mutes or unmutes the local outbound audio track.\n\n```json\n{ "muted": true }\n```',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: {
      muted: true,
    },
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_calls_callId_recording',
    method: 'GET',
    path: '/v1/calls/{callId}/recording',
    summary: 'Download call recording (WAV)',
    description:
      'Streams the stored WAV when call recording was enabled and capture completed. Requires media storage and softphone/stream to capture the local leg.',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: null,
    responses: ['404'],
  },
  {
    id: 'post-_v1_calls_blast',
    method: 'POST',
    path: '/v1/calls/blast',
    summary: 'Audio blast — call + play predefined audio + record response',
    description:
      'Outbound VoIP **audio blast**: dial → wait for answer → play WAV → optional remote-leg record + Whisper STT.\n\n### Audio\n- **WAV only** (PCM 8/16/24/32-bit or float32). Any rate/channels → resampled to **16 kHz mono**.\n- Provide **one** of: `audioUrl` (HTTPS, SSRF-guarded), `mediaBase64`, or multipart field `file` / `audio`.\n- Size caps: blast WAV download limit (~20 MiB) and env `MEDIA_UPLOAD_MAX_BYTES` for uploads.\n\n### Recording & STT\n- With `recordResponse` (default true) the remote PCM is stored and linked on the call row — `GET .../calls/{callId}/recording` and `POST .../transcribe` work afterwards.\n- Transcription runs when `transcribe` is not false **and** `STT_ENABLED` + `STT_API_URL` + `STT_API_KEY` are set (Groq Whisper recommended).\n\n### Timeouts\nThe HTTP request stays open until the blast finishes. Raise your client timeout for long WAVs (`callTimeoutMs` + audio duration + `responseTimeoutMs`).\n\n**Example**\n```bash\ncurl -s -X POST "$BASE/v1/instances/sales-1/calls/blast" \\\n  -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n  -d \'{"to":"5511999999999","audioUrl":"https://cdn.example.com/prompt.wav","responseTimeoutMs":5000,"recordResponse":true,"transcribe":true,"sttLanguage":"pt"}\'\n```',
    tags: ['Calls'],
    security: true,
    params: [],
    bodyExample: {
      to: '5511888888888',
      audioUrl: 'https://example.com/message.wav',
      responseTimeoutMs: 5000,
      callTimeoutMs: 30000,
      recordResponse: true,
      transcribe: true,
      sttLanguage: 'pt',
    },
    responses: ['200', '400', '401', '403', '404', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_calls_callId_transcribe',
    method: 'POST',
    path: '/v1/calls/{callId}/transcribe',
    summary: 'Transcribe a call recording (STT via Groq / OpenAI-compatible)',
    description:
      'Runs speech-to-text on a **stored call recording** (`recordingStatus=ready`) via a Groq/OpenAI-compatible API.\n\n### Env\n| Var | Role |\n| --- | --- |\n| `STT_ENABLED` | must be `true` |\n| `STT_API_URL` | base URL, e.g. `https://api.groq.com/openai` |\n| `STT_API_KEY` | Bearer token |\n| `STT_MODEL` | default `whisper-large-v3` |\n| `STT_LANGUAGE` | optional ISO 639-1 hint |\n\nRecordings come from **audio blast** (`POST .../calls/blast`) or softphone call-recording.\n\n**Example**\n```bash\ncurl -s -X POST "$BASE/v1/instances/sales-1/calls/$CALL_ID/transcribe" \\\n  -H "X-Api-Key: $KEY"\n```',
    tags: ['Calls'],
    security: true,
    params: ['callId'],
    bodyExample: null,
    responses: ['200', '400', '401', '403', '404', '503'],
  },
  {
    id: 'get-_v1_chats',
    method: 'GET',
    path: '/v1/chats',
    summary: 'List chats',
    description:
      'Returns chat projections. **merge=true (default)** collapses multiple `@lid` rows that map to the same phone JID ( style), preferring `@s.whatsapp.net`.',
    tags: ['Chats'],
    security: true,
    params: ['limit', 'offset', 'archived', 'merge'],
    bodyExample: null,
    responses: ['200', '401'],
  },
  {
    id: 'post-_v1_chats_reconcile-lids',
    method: 'POST',
    path: '/v1/chats/reconcile-lids',
    summary: 'Reconcile LID→PN chats',
    description: 'Rebuilds lid_map from contacts, merges duplicate LID/PN conversations, deletes empty LID ghosts.',
    tags: ['Chats'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_chats_chatId',
    method: 'GET',
    path: '/v1/chats/{chatId}',
    summary: 'Get chat',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200', '404'],
  },
  {
    id: 'delete-_v1_chats_chatId',
    method: 'DELETE',
    path: '/v1/chats/{chatId}',
    summary: 'Delete chat from local store',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_chats_chatId_messages',
    method: 'GET',
    path: '/v1/chats/{chatId}/messages',
    summary: 'List chat messages',
    description: 'Paginated history (newest first). Includes messages stored under any LID alias of the chat.',
    tags: ['Chats'],
    security: true,
    params: ['limit', 'before', 'after', 'downloadMedia', 'chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_chats_chatId_messages_messageId',
    method: 'GET',
    path: '/v1/chats/{chatId}/messages/{messageId}',
    summary: 'Get message by id',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId', 'messageId'],
    bodyExample: null,
    responses: ['200', '404'],
  },
  {
    id: 'post-_v1_chats_chatId_messages_read',
    method: 'POST',
    path: '/v1/chats/{chatId}/messages/read',
    summary: 'Mark chat messages as read',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_chats_chatId_archive',
    method: 'POST',
    path: '/v1/chats/{chatId}/archive',
    summary: 'Archive chat',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_chats_chatId_unarchive',
    method: 'POST',
    path: '/v1/chats/{chatId}/unarchive',
    summary: 'Unarchive chat',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_chats_chatId_unread',
    method: 'POST',
    path: '/v1/chats/{chatId}/unread',
    summary: 'Mark chat as unread (app-state)',
    description: '',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_chats_chatId_history-sync',
    method: 'POST',
    path: '/v1/chats/{chatId}/history-sync',
    summary: 'Request on-demand history sync for a chat',
    description:
      'Asks WhatsApp to backfill older messages via `message.requestHistorySync`. Chunks arrive as `history.sync` events.',
    tags: ['Chats'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_groups',
    method: 'GET',
    path: '/v1/groups',
    summary: 'List groups',
    description: '',
    tags: ['Groups'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '503'],
  },
  {
    id: 'post-_v1_groups',
    method: 'POST',
    path: '/v1/groups',
    summary: 'Create group',
    description: '',
    tags: ['Groups'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_groups_groupId',
    method: 'GET',
    path: '/v1/groups/{groupId}',
    summary: 'Get group metadata',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_leave',
    method: 'POST',
    path: '/v1/groups/{groupId}/leave',
    summary: 'Leave group',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_subject',
    method: 'PUT',
    path: '/v1/groups/{groupId}/subject',
    summary: 'Set group subject',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_description',
    method: 'PUT',
    path: '/v1/groups/{groupId}/description',
    summary: 'Set group description',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_groups_groupId_invite-code',
    method: 'GET',
    path: '/v1/groups/{groupId}/invite-code',
    summary: 'Get invite code',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_invite-code_revoke',
    method: 'POST',
    path: '/v1/groups/{groupId}/invite-code/revoke',
    summary: 'Revoke invite code',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_join',
    method: 'POST',
    path: '/v1/groups/join',
    summary: 'Join group via invite code',
    description: '',
    tags: ['Groups'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_groups_join-info',
    method: 'GET',
    path: '/v1/groups/join-info',
    summary: 'Preview group invite',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['code'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_participants_add',
    method: 'POST',
    path: '/v1/groups/{groupId}/participants/add',
    summary: 'Add participants',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_participants_remove',
    method: 'POST',
    path: '/v1/groups/{groupId}/participants/remove',
    summary: 'Remove participants',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_admin_promote',
    method: 'POST',
    path: '/v1/groups/{groupId}/admin/promote',
    summary: 'Promote admins',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_groups_groupId_admin_demote',
    method: 'POST',
    path: '/v1/groups/{groupId}/admin/demote',
    summary: 'Demote admins',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_groups_groupId_picture',
    method: 'GET',
    path: '/v1/groups/{groupId}/picture',
    summary: 'Get group picture',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['type', 'groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_picture',
    method: 'PUT',
    path: '/v1/groups/{groupId}/picture',
    summary: 'Set group picture (URL, base64, or multipart file)',
    description:
      'JPEG group avatar. JSON: `mediaUrl` or `mediaBase64`. Multipart: field `file` (aliases `media`/`image`). Max size: env `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n\n```bash\ncurl -s -X PUT "$BASE/v1/groups/$GID/picture" -H "X-Api-Key: $KEY" -F file=@./group.jpg\n```',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'delete-_v1_groups_groupId_picture',
    method: 'DELETE',
    path: '/v1/groups/{groupId}/picture',
    summary: 'Delete group picture',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_settings_setting',
    method: 'PUT',
    path: '/v1/groups/{groupId}/settings/{setting}',
    summary: 'Toggle group setting',
    description:
      'Settings: `announcement` (messages admin-only), `restrict` (info admin-only), `ephemeral`, `membership_approval_mode`, `group_history`, etc.',
    tags: ['Groups'],
    security: true,
    params: ['groupId', 'setting'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_settings_security_messages-admin-only',
    method: 'PUT',
    path: '/v1/groups/{groupId}/settings/security/messages-admin-only',
    summary: 'Messages admin-only (announcement)',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_groups_groupId_settings_security_info-admin-only',
    method: 'PUT',
    path: '/v1/groups/{groupId}/settings/security/info-admin-only',
    summary: 'Group info admin-only (restrict)',
    description: '',
    tags: ['Groups'],
    security: true,
    params: ['groupId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_profile',
    method: 'GET',
    path: '/v1/profile',
    summary: 'Get own profile snapshot',
    description:
      'Returns the linked account profile, **aligned with `GET /v1/instance`**:\n\n- `pushName` / `avatarUrl` from credentials + durable storage (same enrichment as instance get)\n- `status` = WhatsApp About text (best-effort IQ)\n- `picture` = WA envelope when available; `url` prefers durable `avatarUrl`\n\nUses **bare PN JID** (device suffix stripped) for status/picture IQs — device JIDs often return empty.\n\n```bash\ncurl -s "$BASE/v1/profile" -H "X-Api-Key: $INSTANCE_API_KEY"\n```',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '503'],
  },
  {
    id: 'put-_v1_profile_name',
    method: 'PUT',
    path: '/v1/profile/name',
    summary: 'Set push name (display name)',
    description:
      'Updates the WhatsApp **push name** (display name shown to contacts).\n\nBody: `{ "name": "…" }` or `{ "pushName": "…" }` (max 25 characters).\n\nAlso persists on the instance row so list/get return the new `pushName`.\n\n**Paths**\n- Named: `PUT /v1/instances/:name/profile/name`\n- Short (instance key): `PUT /v1/profile/name`\n\n```bash\ncurl -s -X PUT "$BASE/v1/profile/name" \\\n  -H "X-Api-Key: $INSTANCE_API_KEY" -H "content-type: application/json" \\\n  -d \'{"name":"Loja Sales"}\'\n```',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: {
      name: 'Loja Sales',
    },
    responses: ['200', '400', '401', '403', '503'],
  },
  {
    id: 'put-_v1_profile_image',
    method: 'PUT',
    path: '/v1/profile/image',
    summary: 'Set profile picture (avatar)',
    description:
      'Updates the WhatsApp **profile picture** (avatar).\n\nMedia source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n**Paths** (identical handlers)\n- `PUT /v1/profile/image` (preferred) · alias `PUT /v1/profile/picture`\n\n```bash\ncurl -s -X PUT "$BASE/v1/profile/image" \\\n  -H "X-Api-Key: $INSTANCE_API_KEY" -H "content-type: application/json" \\\n  -d \'{"mediaUrl":"https://cdn.example.com/avatar.jpg"}\'\n\ncurl -s -X PUT "$BASE/v1/profile/image" -H "X-Api-Key: $INSTANCE_API_KEY" \\\n  -F file=@./avatar.jpg\n```',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: {
      mediaUrl: 'https://cdn.example.com/avatar.jpg',
    },
    responses: ['200', '400', '401', '403', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'delete-_v1_profile_image',
    method: 'DELETE',
    path: '/v1/profile/image',
    summary: 'Delete profile picture (alias of /profile/picture)',
    description: '',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '503'],
  },
  {
    id: 'put-_v1_profile_picture',
    method: 'PUT',
    path: '/v1/profile/picture',
    summary: 'Set profile picture (alias of /profile/image)',
    description:
      'Updates the WhatsApp **profile picture** (avatar).\n\nMedia source (one of):\n- JSON `mediaUrl` — public HTTPS URL (SSRF-guarded download)\n- JSON `mediaBase64` — raw or data-URL base64\n- `multipart/form-data` file field `file` (aliases: `media`, `audio`, `image`, `document`, `video`, `sticker`) plus text fields for the rest of the body\n\nMax size: `MEDIA_UPLOAD_MAX_BYTES` (default 100 MiB).\n**Paths** (identical handlers)\n- `PUT /v1/profile/image` (preferred) · alias `PUT /v1/profile/picture`\n\n```bash\ncurl -s -X PUT "$BASE/v1/profile/image" \\\n  -H "X-Api-Key: $INSTANCE_API_KEY" -H "content-type: application/json" \\\n  -d \'{"mediaUrl":"https://cdn.example.com/avatar.jpg"}\'\n\ncurl -s -X PUT "$BASE/v1/profile/image" -H "X-Api-Key: $INSTANCE_API_KEY" \\\n  -F file=@./avatar.jpg\n```',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: {
      mediaUrl: 'https://cdn.example.com/avatar.jpg',
    },
    responses: ['200', '400', '401', '403', '503'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'delete-_v1_profile_picture',
    method: 'DELETE',
    path: '/v1/profile/picture',
    summary: 'Delete profile picture',
    description:
      'Removes the WhatsApp profile picture.\n\n**Also:** `DELETE /v1/profile/image` (alias).\n**Short form (instance key):** `DELETE /v1/profile/picture` or `/v1/profile/image`',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '401', '403', '503'],
  },
  {
    id: 'put-_v1_profile_status',
    method: 'PUT',
    path: '/v1/profile/status',
    summary: 'Set about status',
    description:
      'Updates the WhatsApp **About** text (status string).\n\n**Short form (instance key):** `PUT /v1/profile/status`',
    tags: ['Profile'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200', '400', '401', '403', '503'],
  },
  {
    id: 'get-_v1_privacy',
    method: 'GET',
    path: '/v1/privacy',
    summary: 'Get privacy settings',
    description: '',
    tags: ['Privacy'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_privacy',
    method: 'POST',
    path: '/v1/privacy',
    summary: 'Set one privacy setting',
    description: '',
    tags: ['Privacy'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_business_profile',
    method: 'POST',
    path: '/v1/business/profile',
    summary: 'Fetch business profiles for JIDs/phones',
    description: '',
    tags: ['Business'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_business_profile_phone',
    method: 'GET',
    path: '/v1/business/profile/{phone}',
    summary: 'Fetch one business profile',
    description: '',
    tags: ['Business'],
    security: true,
    params: ['phone'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_status_send',
    method: 'POST',
    path: '/v1/status/send',
    summary: 'Publish a status / story broadcast',
    description:
      'Uses `client.status.send`. Provide `text` and/or media (`mediaUrl` / `mediaBase64` / multipart `file`). `recipients` is the fan-out list required by zapo. Max media size: MEDIA_UPLOAD_MAX_BYTES.',
    tags: ['Status'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
    notes: ['Also accepts multipart/form-data with binary field `file` (see OpenAPI content types).'],
  },
  {
    id: 'post-_v1_status_revoke',
    method: 'POST',
    path: '/v1/status/revoke',
    summary: 'Revoke a published status',
    description: '',
    tags: ['Status'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_status_privacy',
    method: 'POST',
    path: '/v1/status/privacy',
    summary: 'Set status distribution privacy',
    description: '',
    tags: ['Status'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_status_mute',
    method: 'POST',
    path: '/v1/status/mute',
    summary: 'Mute / unmute a contact status',
    description: '',
    tags: ['Status'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_labels',
    method: 'GET',
    path: '/v1/labels',
    summary: 'List labels',
    description: 'WhatsApp Business labels (app-state LabelEdit). Stored locally + synced via chat.set.',
    tags: ['Labels'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_labels',
    method: 'POST',
    path: '/v1/labels',
    summary: 'Create / upsert label',
    description: '',
    tags: ['Labels'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_labels_labelId',
    method: 'PUT',
    path: '/v1/labels/{labelId}',
    summary: 'Update label',
    description: '',
    tags: ['Labels'],
    security: true,
    params: ['labelId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'delete-_v1_labels_labelId',
    method: 'DELETE',
    path: '/v1/labels/{labelId}',
    summary: 'Delete label',
    description: '',
    tags: ['Labels'],
    security: true,
    params: ['labelId'],
    bodyExample: null,
    responses: ['200', '404'],
  },
  {
    id: 'post-_v1_labels_labelId_chats',
    method: 'POST',
    path: '/v1/labels/{labelId}/chats',
    summary: 'Associate / remove label on a chat',
    description: '',
    tags: ['Labels'],
    security: true,
    params: ['labelId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_labels_labelId_chats',
    method: 'GET',
    path: '/v1/labels/{labelId}/chats',
    summary: 'List chats with this label',
    description: '',
    tags: ['Labels'],
    security: true,
    params: ['labelId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_chats_chatId_labels',
    method: 'GET',
    path: '/v1/chats/{chatId}/labels',
    summary: 'List labels on a chat',
    description: '',
    tags: ['Labels'],
    security: true,
    params: ['chatId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_lids',
    method: 'GET',
    path: '/v1/lids',
    summary: 'List LID ↔ phone mappings',
    description:
      'multi-config LID directory from app_contacts + zapo mailbox_contacts.\nPopulated as contacts/history/usync resolve PN↔LID pairs.',
    tags: ['Lids'],
    security: true,
    params: ['limit', 'offset'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_lids_count',
    method: 'GET',
    path: '/v1/lids/count',
    summary: 'Count known LIDs',
    description: '',
    tags: ['Lids'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_lids_pn_phone',
    method: 'GET',
    path: '/v1/lids/pn/{phone}',
    summary: 'Get LID by phone number',
    description: '',
    tags: ['Lids'],
    security: true,
    params: ['phone'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_lids_lid',
    method: 'GET',
    path: '/v1/lids/{lid}',
    summary: 'Get phone number by LID',
    description: '',
    tags: ['Lids'],
    security: true,
    params: ['lid'],
    bodyExample: null,
    responses: ['404'],
  },
  {
    id: 'get-_v1_webhooks',
    method: 'GET',
    path: '/v1/webhooks',
    summary: 'List webhooks (multi-config multi-config)',
    description: 'Multiple webhook endpoints per instance with per-URL events, HMAC, retries, and custom headers.',
    tags: ['Webhooks'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_webhooks',
    method: 'POST',
    path: '/v1/webhooks',
    summary: 'Create webhook config',
    description: '',
    tags: ['Webhooks'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_webhooks_webhookId',
    method: 'GET',
    path: '/v1/webhooks/{webhookId}',
    summary: 'Get webhook',
    description: '',
    tags: ['Webhooks'],
    security: true,
    params: ['webhookId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'put-_v1_webhooks_webhookId',
    method: 'PUT',
    path: '/v1/webhooks/{webhookId}',
    summary: 'Update webhook',
    description: '',
    tags: ['Webhooks'],
    security: true,
    params: ['webhookId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'delete-_v1_webhooks_webhookId',
    method: 'DELETE',
    path: '/v1/webhooks/{webhookId}',
    summary: 'Delete webhook',
    description: '',
    tags: ['Webhooks'],
    security: true,
    params: ['webhookId'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_messages_messageId_media',
    method: 'GET',
    path: '/v1/messages/{messageId}/media',
    summary: 'Download media for a message (original filename)',
    description:
      'Authorizes access, ensures the object exists in storage, then **redirects (302)** to storage\nwhen possible (default) so file bytes do not transit the API.\n\nIf the CAS object was deleted from storage, the API **re-downloads from WhatsApp** (using\nthe stored message `raw`), re-uploads to storage, then redirects/streams. Only fails if\nWhatsApp can no longer provide the media.\n\n- **S3/MinIO:** presigned GET with original filename (ResponseContentDisposition).\n- **`?proxy=1`:** stream through the API (no redirect).\n- **`?download=1`:** attachment disposition.',
    tags: ['Media'],
    security: true,
    params: ['download', 'proxy', 'messageId'],
    bodyExample: null,
    responses: ['404'],
  },
  {
    id: 'get-_v1_media_instance_key',
    method: 'GET',
    path: '/v1/media/{instance}/{key}',
    summary: 'Get media by storage key',
    description: '',
    tags: ['Media'],
    security: true,
    params: ['instance', 'key'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'post-_v1_media_getBase64FromMediaMessage',
    method: 'POST',
    path: '/v1/media/getBase64FromMediaMessage',
    summary: 'Get media as base64 (API parity)',
    description:
      'Downloads media for a message id (from storage if present, else live decrypt via client). Mirrors `chat/getBase64FromMediaMessage`.',
    tags: ['Media'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['404'],
  },
  {
    id: 'post-_v1_chat_getBase64FromMediaMessage',
    method: 'POST',
    path: '/v1/chat/getBase64FromMediaMessage',
    summary: 'Alias: getBase64FromMediaMessage (legacy path)',
    description: '',
    tags: ['Media'],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_events',
    method: 'GET',
    path: '/v1/events',
    summary: 'SSE event stream (server → client)',
    description:
      'Unidirectional live event stream (messages, connection, presence, calls, …).\n\n**Auth: put the API key in headers**, not in the URL (avoids access logs, proxies, Referer).\n\n### curl (recommended)\n```bash\ncurl -N -H "X-Api-Key: $KEY" -H "Accept: text/event-stream" \\\n  "$BASE/v1/events?instance=sales-1"\n```\n\n### Browser (fetch + stream — can send headers)\n```js\nconst res = await fetch(`/v1/events?instance=sales-1`, {\n  headers: { "X-Api-Key": key, Accept: "text/event-stream" },\n})\n// read res.body with TextDecoder…\n```\n\nNative `EventSource` cannot set headers — only then use `?apiKey=` (discouraged).\n\n- **Instance keys** are always scoped to their instance.\n- **Admin** may omit `instance` (all) or filter with `instance=`.\n- First event: `{ "event": "connected", "role", "instance", "timestamp" }`.\n- Keepalive: SSE comments every 15s (`: ping …`).',
    tags: ['Realtime'],
    security: true,
    params: ['apiKey', 'instance'],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_guide',
    method: 'GET',
    path: '/guide',
    summary: '',
    description: '',
    tags: [],
    security: true,
    params: [],
    bodyExample: null,
    responses: ['200'],
  },
  {
    id: 'get-_v1_instances_name_calls_callId_stream',
    method: 'GET',
    path: '/v1/instances/{name}/calls/{callId}/stream',
    summary: 'WebSocket live PCM audio stream',
    description:
      '**WebSocket upgrade** for bidirectional live VoIP audio (not a plain HTTP JSON response).\n\n### URL\n```\nws(s)://<host>/v1/instances/{name}/calls/{callId}/stream?apiKey=<key>\n```\n\nAuth: query `apiKey` (browsers) and/or header `X-Api-Key`.\n\n### Protocol\n1. Server → JSON text: `{ "op": "ready", "sampleRate": 16000, "channels": 1, "format": "f32le", "callId": "..." }`\n2. Client → server **binary**: Float32 LE mono PCM @ 16 kHz (microphone)\n3. Server → client **binary**: same format (peer audio)\n4. Backpressure JSON: `{ "op": "backpressure", "pause": true | false, "bufferedMs": N }`\n5. End: `{ "op": "ended", "callId": "..." }` then socket close\n\nUses `setExternalAudioMode` — **no file autoplay**. Multi-call supported up to `VOIP_MAX_CONCURRENT_CALLS`.',
    tags: ['Calls'],
    security: true,
    params: ['name', 'callId', 'apiKey'],
    bodyExample: null,
    responses: ['101', '401', '403', '404'],
  },
]
